---
# tasks file for apigateway
#- name: execute script file
#  shell: /var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh
#  dest=/etc/ntp.conf mode=644 owner=root group=root
#  register: install

#- name: execute script
#  script: /var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh -f ans-test.html
#  args:
#    chdir: /home/vagrant
#    creates: /home/vagrant/ans-test.html
#  register: install
#  retries: 30
#  delay: 1

#- debug: msg="{{ install.stdout }}"

- name: Copy package to target machines
  synchronize: src=/var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh dest=/var/tmp/
  register: result_copy

- name: Run installation and verification script
  script: /var/tmp/info.sh
  register: result_run
  when: result_copy.changed

- name: Show result
  debug: msg="{{ result_run.stdout }}"