---
# tasks file for apigateway
#- name: execute script file
#  shell: /var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh
#  dest=/etc/ntp.conf mode=644 owner=root group=root
#  register: install

- name: execute script
  script: /var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh -f ans-test.html
  #chdir: /home/vagrant
  args:
    creates: /home/vagrant/ans-test.html
  register: install
  retries: 30
  delay: 1

#- debug: msg="{{ install.stdout }}"

#- name: copy scripts to host
#  copy:
#    src: /var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh
#    dest: /tmp/info.sh
#    owner: vagrant
#    group: vagrant
#    mode: 0755

#- name: show file
#  command: ls -l /tmp
#  register: install

#- debug: msg="{{ install.stdout }}"

#- name: run script
#  script:
#    cmd: /tmp/info.sh ansible-test.html
#    remote_src: yes
#  register: script

#- debug: msg="{{ script.stdout }}"