---
# tasks file for apigateway
#- name: execute script file
#  shell: /var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh
#  dest=/etc/ntp.conf mode=644 owner=root group=root
#  register: install

#- name: execute script
#  script: /var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh -f ans-test.html
#  args:
#    chdir: /home/vagrant
#    creates: /home/vagrant/ans-test.html
#  register: install
#  retries: 30
#  delay: 1

#- debug: msg="{{ install.stdout }}"
- name: Create simon directory
  file:
    path: /home/vagrant/simon
    state: directory
    mode: '0755'

- name: Transfer executable script script
  copy: src=/var/lib/jenkins/workspace/simple-maven-app-ansible/deploy/roles/apigateway/files/info.sh dest=/home/vagrant/simon mode=0777

- name: Execute the script
  command: sh /home/vagrant/simon/info.sh -f {{ output_file }}
  args:
    chdir: /home/vagrant/simon
    creates: /home/vagrant/simon/{{ output_file }}

- name: Show files
  command: ls -la
  args:
    chdir: /home/vagrant/simon
  #register: show

#- debug: msg="{{ show.stdout }}"