node {
    
    stage 'checkout'
    checkout scm
    
    stage 'Build'
    def mvnContainer = docker.image('maven:3-alpine')
    mvnContainer.inside('-v /m2repo:/m2repo') {
    
        sh 'mvn -B -DskipTests clean package'
    }

}
